apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: akv2k8s-controller
  labels:
    app.kubernetes.io/name: akv2k8s
    app.kubernetes.io/instance: akv2k8s
subjects:
- kind: ServiceAccount
  name: akv2k8s-controller
  namespace: akv2k8s
roleRef:
  kind: ClusterRole
  name: akv2k8s-controller
  apiGroup: rbac.authorization.k8s.io
