apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: akv2k8s-controller-reader
  labels:
    app.kubernetes.io/name: akv2k8s
    app.kubernetes.io/instance: akv2k8s
rules:
- apiGroups:
  - spv.no
  resources:
  - azurekeyvaultsecrets
  verbs:
  - get
  - list
  - watch
