apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: akv2k8s-controller
  labels:
    app.kubernetes.io/name: akv2k8s
    app.kubernetes.io/instance: akv2k8s
rules:
- apiGroups:
  - spv.no
  resources:
  - azurekeyvaultsecrets
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - spv.no
  resources:
  - azurekeyvaultsecrets/status
  verbs:
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - create
  - update
  - delete
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - patch
